### ISSUE TITLE
Open Debugger at right commit/folder

### ISSUE THREAD

**Issue by kilianc** [googleapis/cloud-debug-nodejs#460]
Using `source-context.json` I was able to get the debug UI to pick the right commit for me. I am working on a monorepo most of the time and it would be nice to open the debugger at the folder where my code is.

I tried `appPathRelativeToRepository` with no apparent effect.

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  I agree this would be a nice feature to have.  We will talk with the UI team to see if this is possible and will keep this thread updated.  Thanks.

**Comment by ofrobots** [comment]
Hi @kilianc. Sorry for the late response here. Quick question.. you mention that you have a monorepo. What does the source look in the deployment environment? Do you deploy the entire monorepo but modify the start command to run in the right subdirectory? Or do you deploy only a subdirectory?

**Comment by kilianc** [comment]
Hi @ofrobots! One app per folder and everything is containerized and pushed to k8s. In the build scripts we create a specific `source-context.json`.

**Comment by ofrobots** [comment]
@kilianc Thanks a lot. When you say "open the debugger at the folder where my code is", do you mean the UI to directly focus the correct directory in your repo? I may have incorrectly assumed the issue to be originally about a problem that you're unable to hit breakpoints because the debugger might be confused by multiple files with the same name (e.g. `index.js`).

**Comment by ofrobots** [comment]
Re-reading OP, it is quite clear that this is about the UI – sorry about that. Let me open a bug against the UI team.

**Comment by ofrobots** [comment]
Opened bug :https://issuetracker.google.com/124381769
