### ISSUE TITLE
Add a way to access the singleton after initialization

### ISSUE THREAD

**Issue by jpreynat** [googleapis/cloud-debug-nodejs#705]
**Is your feature request related to a problem? Please describe.**

To use the module inside cloud functions, it is required that:
1/ The module is loaded before anything else
2/ The `debug.isReady()` promise should resolve before exiting the cloud function

However, in a complex NodeJS app with multiple functions, the code for 1/ and 2/ never lives in the same file.

 **Describe the solution you'd like**

As for the `@google-cloud/trace-agent`, the usage would be greatly simplified if the module exported a `get()` method to access the singleton instance from anywhere.

**Comment by DominicKramer** [comment]
Thanks for the feedback.  Using `require('@google-cloud/debug-agent').start()` returns an object that could be passed to functions that need it using a dependency injection approach.  Would that approach work?

I don't think having a get method would be good because the `get` method would only be something that could be called after `start` has been called.  Another approach would have `start` return the same singleton if called multiple times, but calling start multiple times seems like a strange API usage.

**Comment by jpreynat** [comment]
What I need to do is start the debug agent and be able to access the singleton in another module that is `require`d at runtime, so passing it is not optional.
Calling `start` multiple times would indeed be a weird API. But the singleton could simply be exported from the module and `isReady` should only trigger once `start` has been called.

**Comment by jpreynat** [comment]
Just wanted to check if there is any news regarding this issue?

**Comment by DominicKramer** [comment]
After thinking about this more, I'm planning on addressing your issue by adding a `get()` function that returns the agent if it has been started or `undefined` if it hasn't.  It would be the caller's responsibility to check the return value and start the agent if needed.  This makes the interface simple.

**Comment by DominicKramer** [comment]
PR #709 has been opened that adds the `get()` function.  However, there are some unrelated test failures that need to be resolved before landing the change.

**Comment by DominicKramer** [comment]
PR #709 has landed that addresses this issue.  I release containing the fix will arrive soon.

**Comment by DominicKramer** [comment]
Version 4.0.0 has just been released that addresses this issue.
