### ISSUE TITLE
Line 1 breakpoint locations may no longer be accurate after 10.16+

### ISSUE THREAD

**Issue by kjin** [googleapis/cloud-debug-nodejs#737]
A failing test ([testing setting line-1 breakpoints](https://github.com/googleapis/cloud-debug-nodejs/blob/bb1bcc93c2ebbd021dc193d615b7086ae5857349/test/test-v8debugapi.ts#L1822)) that is the cause of #729 highlights a potentially breaking change for us in Node 10.16: scripts are now parsed slightly differently. Consider the following code:

```
module.exports = function foo(n) { return n; }
```

In Node 10.15 and below, getting the above script via Inspector's `Debugger.getScriptSource` yields:

```
(function (exports, require, module, __filename, __dirname) { module.exports = function foo(n) { return n; }
});
```

In Node 10.16+, it yields the original source:

```
module.exports = function foo(n) { return n; }
```

This almost certainly affects line-1 breakpoints.

**Comment by kjin** [comment]
This issue should not be closed until the test skipped in #738 is re-enabled.

**Comment by bcoe** [comment]
@kjin interesting, I remember when this was introduced, `compileFunction` is now used:

https://github.com/nodejs/node/blob/master/lib/internal/modules/cjs/loader.js#L856

rather than source being pre-wrapped with a wrapper, this should ultimately help ensure slightly more accurate information, but it does mean that prior to Node.10.16 the wrapper exists afterwords it does not.

**Comment by kjin** [comment]
@bcoe Thanks, I found the PR that caused this change: https://github.com/nodejs/node/pull/21573
