### ISSUE TITLE
Debugging dynamically imported files

### ISSUE THREAD

**Issue by merlinnot** [googleapis/cloud-debug-nodejs#762]
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 10.15.3
  - npm version: 6.11.2
  - `@google-cloud/debug-agent` version: 4.0.3

#### Steps to reproduce

First off, you did such an amazing job with this product! Love it! I have a small issue tho. I can set breakpoints easily for files that are required from `index.js`, but I have some files that are required later on for some specific requests (the app is running and when a request hits, it might decide to require some additional files) - and for these dynamically required breakpoints and logpoints don't work. Here's a small example:

```js
// index.js - breakpoints work
const run = () => {
  const dynamic = require('./dynamic.js);

  dynamic();
}

// dynamic.js - breakpoints don't work, even tho the code is executed
module.exports = () => {
  console.log('I am doing stuff.);
}
```

**Comment by DominicKramer** [comment]
Thanks for the feedback.  We really appreciate it.  I was able to make an example with dynamic imports where breakpoints are hit correctly.

Here is what I think is happening with your example:

The debug agent runs in the running application.  When a snapshot is set (either through the gcloud CLI or Google Cloud UI), the agent in the running application is notified and the agent sets a snapshot at the specified line.  Then when the line is hit, the snapshot is triggered.  This notification process is not instantaneous.

As such, if a snapshot is set at the first statements in an application, the agent might not have yet received info from the Debug API to set the snapshot.  As such, the snapshot is not triggered because when the line is reached in the application, the debug agent does not yet know it should have a breakpoint hit at that line.

If the line could be reached a second time, after the agent had received breakpoint data, then the snapshot would hit.  Often times snapshots are set in routes in an express app (for example).  Thus, if the first time the route is encountered and snapshot doesn't hit (because the agent hasn't received breakpoint data yet), it is fine because the second time the route is hit the breakpoint will be hit.

The example that I have follows this and is an express app that does a require in the "/" route.  In this setup the breakpoint hits correctly.

I hope this helps resolve your issue.  If you have any other problems or questions, just let us know.
